# Generated by Django 4.2.11 on 2024-03-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(default=1, verbose_name=(1, 2, 3, 4, 5)),
            preserve_default=False,
        ),
    ]
