# Generated by Django 4.2.11 on 2024-03-27 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_review_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='produced',
            field=models.DateField(default=datetime.datetime(2024, 3, 27, 19, 17, 35, 597785)),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(verbose_name=(1, 2, 3, 4, 5)),
        ),
    ]
